{
 "title": "Airports analytics",
 "time": { "from": "2023-09-30T21:00:00.000Z", "to": "2023-10-14T21:00:00.000Z" },
 "panels": [
  {
   "title": "Active airports over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH merge_airports AS (\n  SELECT  \n  flight_date,\n  airport_code\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\n\nUNION ALL\n\nSELECT  \n  flight_date,\n  linked_airport_code as airport_code\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\n)\n\nSELECT  \n  flight_date::date,\n  COUNT(DISTINCT airport_code)\nFROM \n  merge_airports\nGROUP BY\n  flight_date::date\nORDER BY\n  flight_date::date\n;"
    }
   ]
  },
  {
   "title": "Active airports - last 30d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH merge_airports AS (\n  SELECT  \n  flight_date,\n  airport_code\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\n\nUNION ALL\n\nSELECT  \n  flight_date,\n  linked_airport_code as airport_code\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\n)\n\nSELECT  \n  COUNT(DISTINCT airport_code)\nFROM \n  merge_airports\n;"
    }
   ]
  },
  {
   "title": "Airports total flights share",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  airport_code,\n  SUM(flights_out + flights_out) as total_flights\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\nGROUP BY\n  airport_code"
    }
   ]
  },
  {
   "title": "Airports total passengers share",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  airport_code,\n  SUM(passengers_in + passengers_out) as total_flights\nFROM \n  presentation.airport_traffic\nWHERE\n  flight_date between $__timeTo()::timestamp - INTERVAL '30 days' AND $__timeTo()::timestamp\nGROUP BY\n  airport_code"
    }
   ]
  }
 ]
}