{
 "title": "Passenger analytics",
 "time": { "from": "2023-10-01T14:00:00.000Z", "to": "2023-10-05T12:00:00.000Z" },
 "panels": [
  {
   "title": "Unique passengers over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT flight_date, SUM(passengers_out) as passengers_cnt FROM presentation.airport_traffic GROUP BY flight_date;"
    }
   ]
  },
  {
   "title": "Unique passengers (30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT passenger_id) FROM presentation.frequent_flyers;"
    }
   ]
  },
  {
   "title": "AVG flights/passenger (30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(flights_number)/COUNT(DISTINCT passenger_id) FROM presentation.frequent_flyers;"
    }
   ]
  },
  {
   "title": "AVG purchase (30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(purchase_sum)/SUM(flights_number) FROM presentation.frequent_flyers;"
    }
   ]
  },
  {
   "title": "Passengers by GMV",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'top ' || customer_group || '%' as customer_group, COUNT(DISTINCT passenger_id) as passengers_cnt FROM presentation.frequent_flyers GROUP BY customer_group ORDER BY customer_group;"
    }
   ]
  }
 ]
}