services:
  postgres_master:
    container_name: postgres_master
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-replica:/var/lib/postgresql/data-replica
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
      - ./ddl_init.sql:/docker-entrypoint-initdb.d/ddl_init.sql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres_replica:
    container_name: postgres_replica
    image: postgres:14.5
    restart: always
    volumes:
      - ./data-replica:/var/lib/postgresql/data
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5433:5432"
    depends_on:
      - postgres_master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
